services:
  spaniej:
    container_name: spaniej
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COOKIE_SECRET: ${COOKIE_SECRET}
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env

networks:
  default:
    external: true
    name: krokosik-web-services